<?php 
$accommodatesAttr = Mage::getModel('eav/config')->getAttribute('catalog_product', Mage::helper('property')->getAccomodatesType());
$acc_default = $accommodatesAttr->getDefaultValue();
$roomsAttr = Mage::getModel('eav/config')->getAttribute('catalog_product', Mage::helper('property')->getRooms());
$roomAvail = $roomsAttr->getDefaultValue();
$entity_id= $this->getRequest()->getParam('id');

$_product = Mage::getModel('catalog/product')->load($entity_id);
$title = $_product->getName();
$price= $_product->getPrice();
$cleaningFee = $_product->getCleaningFee();
$extraFees = $_product->getExtraFees();
$depositAmount = $_product->getDepositAmount();
$description =$_product->getDescription();
$keywords =$_product->getKeywords();
$highlight = $_product->getHouseRule();
$propertytype=$_product->getPropertyType();
$amenity = $_product->getAmenity();
$propertySize = $_product->getPropertySize();
$hostPhoneNum = $_product->getHostContactNumber();
$restriction = $_product->getRestrictions();
$bedroom = $_product->getRoomsAvailable();
$bedtype = $_product->getBedType();
$privacy = $_product->getRoomType();
$city = $_product->getCity();
$state = $_product->getState();
$getcountry = $_product->getCountry(); 
$zipcode = $_product->getZipcode();
$address = $_product->getAddress();
$accomodate = $_product->getAccomodates();
//$pets = $_product->getPets();
$cancelpolicy = $_product->getCancellationPolicy();
$metaTitle = $_product->getMetaTitle();
$metaKeyword = $_product->getMetaKeyword();
$metaDescription = $_product->getMetaDescription();
$get_banner = $_product->getBanner();

$getamenity= explode(',' , $_product->getAmenities());
$getrestriction= explode(',' , $_product->getRestrictions());
$propertytypeId = Mage::helper('property')->getPropertyTypeAttrId();
$amenityId =  Mage::helper('property')->getAmenitiesAttrId();
$restrictionsId =  Mage::helper('property')->getRestrictionsAttrId();
$cancelpolicyId = Mage::helper('property')->getCancellationPolicyAttrId();
$propertytypeAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $propertytypeId);
$amenityAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $amenityId);
$restrictionAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $restrictionsId);

$cancelpolicyAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $cancelpolicyId);
$bedtypeId = Mage::helper('property')->getBedTypeAttrId();
$bedtypeAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $bedtypeId);

$privacyId= Mage::helper('property')->getRoomTypeAttrId();
$privacyAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $privacyId);
$currencyCountry = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getBaseCurrencyCode())->getName();
$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getBaseCurrencyCode())->getShortName();

$PropertyType = array();
$select_protype = '<option value="">'.$this->__('Select').'</option>';
$privacy_select = '<option value="">'.$this->__('Select').'</option>';
foreach ($propertytypeAttribute->getSource()->getAllOptions() as $option) {
    $value = $option['value'];
    if($value !='') {
        $PropertyType[$value] = $option['label'];
        if(($option['value'] == $propertytype)) {
        	$select_protype .= "<option selected value='".$option['value']."'>". $option['label']."</option>";
        } else {
        	$select_protype .= "<option value='".$option['value']."'>". $option['label']."</option>";
        }
    }
}

foreach ($cancelpolicyAttribute->getSource()->getAllOptions() as $cancelpolicy_option) {
    $cancelpolicy_value = $cancelpolicy_option['value'];
    if($cancelpolicy_value !='') {
    	if(($cancelpolicy_option['value'] == $cancelpolicy)) {
        	$cancelpolicy_select .= "<option selected='selected'  value='".$cancelpolicy_option['value']."'>". $cancelpolicy_option['label']."</option>";
        } else {
        	$cancelpolicy_select .= "<option value='".$cancelpolicy_option['value']."'>". $cancelpolicy_option['label']."</option>";
        }
    }
}

$countryList = Mage::getResourceModel('directory/country_collection')
                    ->loadData()
                    ->toOptionArray(false);
foreach ($countryList as $country) {
	 $value = $country['value']; 
     if($value !='') {
    	if(($country['label'] == $getcountry)) {
        	 $countryselect .= "<option selected value='".$country['label']."'>". $country['label']."</option>";
        } else {
        	$countryselect .= "<option value='".$country['label']."'>". $country['label']."</option>";
        }
    }
}

foreach ($bedtypeAttribute->getSource()->getAllOptions() as $bedtype_option) {
    $bedtype_value = $bedtype_option['value'];
    if($bedtype_value !='') {
    	if(($bedtype_option['value'] == $bedtype)) {
        	 $bedtype_select .= "<option selected  value='".$bedtype_option['value']."'>". $bedtype_option['label']."</option>";
        } else {
        	$bedtype_select .= "<option value='".$bedtype_option['value']."'>". $bedtype_option['label']."</option>";
        }
    }
}
foreach ($privacyAttribute->getSource()->getAllOptions() as $privacy_option) {
    $privacy_value = $privacy_option['value'];
    if($privacy_value !='') {
        if(($privacy_option['value'] == $privacy)) {
        	 $privacy_select .= "<option selected  value='".$privacy_option['value']."'>". $privacy_option['label']."</option>";
        } else {
        	$privacy_select .= "<option value='".$privacy_option['value']."'>". $privacy_option['label']."</option>";
        }
    }
}


$banner = Mage::getStoreConfig('property_section/custom_banner/enable_slider_hoster');

?>
<div  class="my-account">
<div class="page-title">
    <h1 ><?php echo $this->__('Edit Your Space') ?></h1>
</div>
    <div class="action_grid">
        <strong class="action_button">
            <a class="icon_list calender" target="_blank" title="Calendar"  onClick="location.href='<?php echo $this->getUrl('property/index/blockcalendar', array('id' => $_product->getId()))?>'"><?php echo $this->__('Calendar') ?></a>
        </strong>
        <strong class="action_button">
            <a class="icon_list gallery_grid" target="_blank" title="Gallery"  onClick="location.href='<?php echo $this->getUrl('property/index/gallery', array('id' => $_product->getId()))?>'" ><?php echo $this->__('Gallery') ?></a>
        </strong>
        <strong class="action_button" style="margin-right: 0;">
            <a class="icon_list review_grid" target="_blank" title="Reviews"  onClick="location.href='<?php echo $this->getUrl('property/index/review', array('id' => $_product->getId()))?>'"><?php echo $this->__('Reviews') ?></a>
        </strong>
        <div class="clear"></div>
    </div>

     <div class="clear"></div>
 <form action="<?php echo $this->getUrl('property/index/update') ?>" id="propertyupdate" name="propertyupdate" method="post" enctype="multipart/form-data">
    <div class="fieldset" style="float:left;">
    <h2 class="legend"><?php echo $this->__('About Your Place'); ?></h2>
    <ul id="list_type_inner">
        <li class="listheading"><h1><?php echo $this->__('Listing Type limit'); ?></h1></li>
        <li>
        	<div class="field">
            	<div class="selectproperty">
					<label for="proptype" class="required left lable_inner"> <?php echo $this->__('Property Type') ?><em>*</em></label>
                	<div class="floatleft">
                		<select id="property_type" name="property_type" class="select select input-text required-entry input-text_pro">
                        	<?php echo $select_protype; ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="selectprivacy">
                	<label for="privacy" class="required left lable_inner"><?php echo $this->__('Room Type') ?> <em>*</em></label>
                    <div class="floatleft">
                    	<select id="room_type" name="room_type" class="select select input-text required-entry input-text_room">
                    		<?php echo $privacy_select; ?>
                   		</select>
                   	</div>
    				<div class="clear"></div>
	            </div>
	            <input name="id" id="id" title="<?php echo $this->__('id') ?>" value="<?php echo $entity_id;?>" type="hidden"/>
	        </div>
    	</li>
    	
        <li class="listheading"><h1><?php $this->__('Description') ?></h1></li>
        <li class="fields">
            <div class="field">
                <div class="input-box_inner">
                	<label for="name" class="required left lable_inner"> <?php echo $this->__('Title') ?> <em>*</em></label>
	                <div class="floatleft">
	                    <input name="name" id="name" title="<?php echo $this->__('Name') ?>" value="<?php echo $title; ?>" class="input-text required-entry validate-length minimum-length-4 maximum-length-35 input-text_inner" type="text" maxlength="100" /><br />
	                    <span><?php echo $this->__('Property title should contains 4-35 letters.'); ?></span>
	                </div>
                </div>
                <div class="input-box_inner">
	                <label for="desc" class="required left lable_inner"><?php echo $this->__('Description') ?> <em>*</em></label>
	                <div class="floatleft"> 
	                	<textarea name="description" id="description" title="<?php echo $this->__('Description') ?>" class="required-entry input-text input-text_descri" cols="5" rows="5"><?php echo $description; ?></textarea>
	                </div>
	            </div>
	            <div class="input-box_inner">
	                <label for="desc" class="required left lable_inner"><?php echo $this->__('Keywords') ?> <em>*</em></label>
	                <div class="floatleft"> 
	                	<textarea name="keywords" id="keywords" title="<?php echo $this->__('Keywords') ?>" class="required-entry input-text input-text_descri" cols="5" rows="5"><?php echo $keywords; ?></textarea>
	                </div>
	            </div>
                <div class="input-box">
	                <label for="sdesc" class="required left lable_inner"><?php echo $this->__('House rules') ?> <em>*</em></label>
	                <div class="floatleft">
	                	<textarea name="house_rule" id="house_rule" title="<?php echo $this->__('House rules') ?>" class="required-entry input-text input-text_high" cols="5" rows="5"><?php echo $highlight; ?></textarea>
	                </div>
	            </div>
            </div>
            <div class="clear"></div>
        </li>
        
        <li class="listheading"><h1><?php echo $this->__('Amenities'); ?></h1></li>
        <li>             
        <?php 
			$totalAmenity = count($amenityAttribute->getSource()->getAllOptions());
			$x = 1;
	            
			foreach ($amenityAttribute->getSource()->getAllOptions() as $amenity) {
	            $value = $amenity['value'];
	            $checkAmenity = $getamenity[$i];
	            if($x == 1)
	                echo "<ul id='amenities_panel'>";
	            if($value !='') {
	            	$PropertyType[$value] = $amenity['label'];
         ?>
                <li class="checkbox lable_inner checkbox_inner">
					<?php if(in_array($amenity['value'],$getamenity)){ ?>
						<input type="checkbox" name="amenity[<?php $i?>]" id="amenity[<?php $i?>]" value="<?php echo $amenity['value']; ?>"  checked="checked" /> <?php echo $amenity['label']; ?>
					<?php } else { ?>
						<input type="checkbox" name="amenity[<?php $i?>]" id="amenity[<?php $i?>]" value="<?php echo $amenity['value']; ?>" /> <?php echo $amenity['label']; ?>
					<?php }?>
                </li>
                <?php }
                  if($x==$totalAmenity) echo "</ul>";
                  	$x++;
              }?>
        </li>
            
        <li class="listheading"><h1><?php echo $this->__('Restrictions'); ?></h1></li>
		<li>             
			<ul class='restriction_panel'>
            <?php 
	            $totalRestriction = count($restrictionAttribute->getSource()->getAllOptions());
	            $x = 1;
              	foreach ($restrictionAttribute->getSource()->getAllOptions() as $restriction) {
                    $value = $restriction['value'];
                    //$checkAmenity = $getamenity[$i];
                    if($value !='') {
            ?>
		                <li class="checkbox lable_inner checkbox_inner">
							<?php if(in_array($restriction['value'],$getrestriction)) { ?>
								<input type="checkbox" name="restriction[<?php $i?>]" id="restriction[<?php $i?>]" value="<?php echo $restriction['value']; ?>"  checked="checked" > <?php echo $restriction['label']; ?>
							<?php } else { ?>
								<input type="checkbox" name="restriction[<?php $i?>]" id="restriction[<?php $i?>]" value="<?php echo $restriction['value']; ?>" /> <?php echo $restriction['label']; ?>
							<?php } ?>
		                </li>
                    <?php }
                }?>
			</ul>
        </li>
            
        <li class="listheading"><h1><?php echo $this->__('Details'); ?></h1></li>
        <li>
            <div class="field">
                <div class="selectaccomodate">
                	<label for="accomodate" class="required left lable_inner"> <?php echo $this->__('Accommodates') ?> <em>*</em></label>
                	<div class="floatleft">
                		<select id="accomodates" name="accomodates"  class="select select input-text required-entry input-text_acc">
                            <?php for($i=1; $i<= $acc_default; $i++) { ?>
                            <option <?php if($accomodate==$i) echo " selected='selected' "; ?> value="<?php echo $i;?>"><?php echo $i;?></option>
                            <?php }?>

                        </select>
                		<span class="info_span"><?php echo $this->__('This refers number of guest allowed in your place'); ?></span>
                	</div>
                </div>
            </div>
           	<div class="field">
               	<div class="selectroom">
	                <label for="room" class="required left lable_inner"><?php echo $this->__('Bed rooms') ?> <em>*</em></label>
	                <div class="floatleft">
	                	<select id="rooms_available" name="rooms_available" class="select select input-text required-entry input-text_bed">
                            <?php for($i=1; $i<= $roomAvail; $i++) { ?>
                            	<option <?php if($bedroom == $i) echo " selected='selected' "; ?> value="<?php echo $i;?>"><?php echo $i;?></option>
                           	<?php }?>
                        </select>
                   		<span class="info_span"><?php echo $this->__('Select the number of bedrooms excluding living rooms.'); ?></span>
                	</div>
                </div>
            </div>
            <div class="field">
                <div class="selectbedtype">
		            <label for="pets" class="required lable_inner left"> <?php echo $this->__('Bed type') ?> <em>*</em></label>
		            <div class="floatleft">
	              		<select id="bed_type" name="bed_type"  class="select select input-text required-entry input-text_bedtype">
                            <option value=""><?php echo $this->__('Select Bed type') ;?></option>
                            <?php echo $bedtype_select; ?>
                        </select>
            		</div>
                </div>
            </div>
                    
            <div class="input-box input-box_inner">
				<label for="property_size" class="required lable_inner left"> <?php echo $this->__('Property Size') ?></label>
				<div class="floatleft">
				<input name="property_size" id="property_size" title="<?php echo $this->__('Property Size') ?>" value="<?php echo $propertySize; ?>" class="input-text" type="text"/>
				 <span class="info_span"> <?php echo $this->__('Enter property size in square feet.'); ?></span>
				</div>
            </div>
            
            <div class="input-box input-box_inner">
              	<label for="price" class="required lable_inner left"> <?php echo $this->__('Price/Night') ?> <em>*</em></label>
              	<div class="floatleft">
	                <input name="price" id="price" title="<?php echo $this->__('Price') ?>" value="<?php echo $price; ?>" class="input-text required-entry validate-greater-than-zero input-text_price " type="text"/>
	                <span class="info_span"> <?php echo  $currencySymbol .'('. $this->__('Enter price in ') . $currencyCountry . ')'; ?></span>
                </div>
            </div>
            <div class="input-box input-box_inner">
              	<label for="cleaning_fee" class="lable_inner left"> <?php echo $this->__('Cleaning Fee') ?></label>
              	<div class="floatleft">
	                <input name="cleaning_fee" id="cleaning_fee" title="<?php echo $this->__('Cleaning Fee') ?>" value="<?php echo $cleaningFee; ?>" class="input-text validate-greater-than-zero input-text_price " type="text"/>
	                <span class="info_span"> <?php echo  $currencySymbol .'('. $this->__('Enter price in ') . $currencyCountry . ')'; ?></span>
                </div>
            </div>
            <div class="input-box input-box_inner">
              	<label for="extra_fees" class="lable_inner left"> <?php echo $this->__('Extra Fees') ?></label>
              	<div class="floatleft">
	                <input name="extra_fees" id="extra_fees" title="<?php echo $this->__('Extra Fees') ?>" value="<?php echo $extraFees; ?>" class="input-text validate-greater-than-zero input-text_price " type="text"/>
	                <span class="info_span"> <?php echo  $currencySymbol .'('. $this->__('Enter price in ') . $currencyCountry . ')'; ?></span>
                </div>
            </div>
            <div class="input-box input-box_inner">
              	<label for="deposit_amount" class="lable_inner left"> <?php echo $this->__('Deposit Amount') ?></label>
              	<div class="floatleft">
	                <input name="deposit_amount" id="deposit_amount" title="<?php echo $this->__('Deposit Amount') ?>" value="<?php echo $depositAmount; ?>" class="input-text validate-greater-than-zero input-text_price " type="text"/>
	                <span class="info_span"> <?php echo  $currencySymbol .'('. $this->__('Enter price in ') . $currencyCountry . ')'; ?></span>
                </div>
            </div>
            <div class="input-box input-box_inner">
              <label for="address" class="required lable_inner left"> <?php echo $this->__('Address') ?> <em>*</em></label>
              <div class="floatleft">
                <textarea name="address" id="address" title="<?php echo $this->__('Address') ?>" class="required-entry input-text input-text_address" cols="5" rows="5"><?php echo $address; ?></textarea>
              </div>
            </div>
            <div class="input-box input-box_inner">
              <label for="city" class="required lable_inner left"> <?php echo $this->__('City') ?> <em>*</em></label>
              <div class="floatleft">
                <input name="city" id="city" title="<?php echo $this->__('City') ?>" value="<?php echo $city; ?>" class="input-text required-entry input-text_city" type="text"/>
              </div>
            </div>
            <div class="input-box input-box_inner">
              <label for="state" class="required lable_inner left"> <?php echo $this->__('State / Province / Region') ?> <em>*</em></label>
                 <div class="floatleft">
                 	<input name="state" id="state" title="<?php echo $this->__('State / Province / Region') ?>" value="<?php echo $state; ?>" class="input-text required-entry input-text_state" type="text"/>
                 </div>
            </div>

            <div class="field">
                <div class="selectpropcountry">
	            	<label for="country" class="required lable_inner left"><?php echo $this->__('Country') ?> <em>*</em> </label>
	            	<div class="floatleft">
	              		<select id="country" name="country"  class="select select input-text required-entry input-text_country">
	                        <option value=""><?php echo $this->__('Select your Country') ;?></option>
	                        <?php echo $countryselect; ?>
	                    </select>
	            	</div>
                </div>
            </div>

            <div class="input-box input-box_inner">
                <div class="selectcontact">
	            	<label for="zipcode" class="required lable_inner left"><?php echo $this->__('Zipcode') ?> <em>*</em> </label>
	            	<div class="floatleft">
	              		<input name="zipcode" id="zipcode" title="<?php echo $this->__('Zipcode') ?>" value="<?php echo $zipcode; ?>" class="input-text required-entry" type="text"/>
	            	</div>
                </div>
            </div>
            
            <div class="input-box input-box_inner">
                <div class="selectcontact">
	            	<label for="host_contact_number" class="required lable_inner left"><?php echo $this->__('Host Contact Number') ?> <em>*</em> </label>
	            	<div class="floatleft">
	              		<input name="host_contact_number" id="host_contact_number" title="<?php echo $this->__('Host Contact Number') ?>" value="<?php echo $hostPhoneNum; ?>" class="input-text required-entry" type="text"/>
	            	</div>
                </div>
            </div>
             
            <div class="field">
            	<div class="selectcancelpolicy">
            		<label for="cancellation_policy" class="required lable_inner left"> <?php echo $this->__('Cancellation Policy') ?> <em>*</em></label>
            		<div class="floatleft">
            			<select id="cancellation_policy" name="cancellation_policy"  class="select select input-text required-entry input-text_policy">
                            <option value=""><?php echo $this->__('Select Cancellation Policy') ;?></option>
                            <?php echo $cancelpolicy_select; ?>
                        </select>
            		</div>
                </div>
            </div>
       
            <?php /*if(empty($banner)) { ?>
                <div class="field">
                   <div class="selectcancelpolicy">
                    <label for="banner" class="required lable_inner left"> <?php echo $this->__('Property Display in Homepage Banner') ?></label>
                     <div class="floatleft">
                         <?php echo $this->__('If Yes'); ?> <input type="checkbox" name="banner" id="banner" value="1" <?php if($get_banner) { echo 'checked="checked"'; } ?> />
                     </div>
                    </div>
                 </div>
             <?php }*/ ?> 

        </li>
        
        <li class="listheading"><h1><?php echo $this->__('Meta Information'); ?></h1></li>
        <li class="field">
        	<div class="field">
            	<div class="input-box_inner">
                	<label for="name" class="required left lable_inner"><em></em><?php echo $this->__('Meta Title') ?></label>
                    <input name="meta_title" id="meta_title" title="<?php echo $this->__('Meta Title') ?>" value="<?php echo $metaTitle; ?>" class="input-text validate-length minimum-length-4 maximum-length-35 input-text_inner" type="text" maxlength="100" />
                </div>
                <div class="input-box_inner">
                    <label for="desc" class="required left lable_inner"><em></em><?php echo $this->__('Meta Keywords') ?></label>
                 		<textarea name="meta_keyword" id="meta_keyword" title="<?php echo $this->__('Meta Keywords') ?>" class="input-text input-text_descri" cols="5" rows="5"><?php echo $metaKeyword; ?></textarea>
                </div>
                <div class="input-box">
                    <label for="sdesc" class="required left lable_inner"><em></em><?php echo $this->__('Meta Description') ?></label>
                    <textarea name="meta_description" id="meta_description" title="<?php echo $this->__('Meta Description') ?>" class="input-text input-text_high" cols="5" rows="5"><?php echo $metaDescription; ?></textarea>
                </div>
            </div>
        </li>
        
        	<div class="buttons-set">
        		<p class="required ">* <?php echo $this->__('Required Fields') ?></p>
        		<div class="page-button" style="float:left;"><a title="Back" href="<?php echo $this->getUrl('property/index/show')?>">Back</a></div>
         		<button type="submit" title="<?php echo $this->__('Update') ?>" class="button"><span><span><?php echo $this->__('Update your property') ?></span></span></button>
    		</div>
    	
    </ul>
    </div>
 </form>
 <div class="clearer"></div>
</div>

<script type="text/javascript">
    //<![CDATA[
    var Propertyform = new VarienForm('propertyupdate', true);
    //]]>
</script>
