<?php
$customerData = $this->getCustomerProfile();
$customer_id = Mage::getSingleton('customer/session')->getId();
$customer = Mage::getModel('customer/customer')->load($customer_id);
//echo '<pre>'; print_r($customer->getData()); echo '</pre>';
?>
<div class="my-account">
    <div class="page-title">
	    <h1><b class="icon_grid edit_id"></b><?php echo $this->__('Edit Profile') ?></h1>
	</div>
	<form action="<?php echo $this->getUrl('customerextend/manage/updatepicture') ?>" method="post" id="profile_picture" enctype="multipart/form-data" >
	    <div class="fieldset">       
	        <h2 class="legend"><?php echo $this->__('Profile Picture') ?></h2>
	        <div class="clear"></div>
	        <ul class="form-list">
	            <li class="fields">
	                <div id="profile_img">
	                <?php
	                if($customerData->getImageName() !="") {
	                      $imageResized = Mage::getBaseDir("media") . "catalog/customer/resz_120_" . $customerData->getImageName();
	                                $imageDirUrl  = Mage::getBaseDir("media") . "catalog/customer/" . $customerData->getImageName();
	                                if (!file_exists($imageResized) && file_exists($imageDirUrl)) :
	                                    $imageObj = new Varien_Image($imageDirUrl);
	                                    $imageObj->constrainOnly(TRUE);
	                                    $imageObj->keepAspectRatio(TRUE);
	                                    $imageObj->keepFrame(FALSE);
	                                    $imageObj->resize(120, 120);
	                                    $imageObj->save($imageResized);
	                                    chmod($imageResized, 0777);
	                                endif;
	                                
	                                $imageUrl = Mage::getBaseUrl('media') . "catalog/customer/" . $customerData->getImageName();
	                                if (file_exists($imageResized)) {
	                                    $imageUrl = Mage::getBaseUrl('media') . "catalog/customer/resz_120_" . $customerData->getImageName();
	                                }
	                                
	                    echo "<img src='$imageUrl' /> ";
	                    echo "<div align='right' style='clear:both;width:100%;
	' ><button style='margin-top:10px;clear:both;width:100% !important; float: left;' type='button' class='button' name='deleteimage' title='".$this->__('Delete')."' onclick='return deleteImage()'><span>".$this->__('Delete')."</span></button></div>";
	                }
	                else{?>
                        	<?php if($customer->getLoginProvider() == 'Facebook' && $customer->getFacebookUserid() != '') { ?>
                        		<img src="https://graph.facebook.com/<?php echo $customer->getFacebookUserid() ?>/picture?type=large"  alt="" class="no_user"/>
                        	<?php } else { ?>
                        		<img src="<?php echo $this->getSkinUrl('images/no_user.jpg') ?>"  alt="" class="no_user"/>
                        	<?php } ?>
	                <?php }
	                ?>
	                </div>
	                <div id="choose_img">
	                     <img src="<?php echo $this->getSkinUrl('images/img_upload.png');?>"  alt=""/>
	                     <span><?php echo $this->__('Upload a file from your computer') ?></span>
	                     <input class="required-file" id="image_name" type="file" name="image_name" value="" />
	                </div>
	                <button type="submit" title="<?php echo $this->__('Change profile image') ?>" class="button right"><span><span><?php echo $this->__('Change profile image') ?></span></span></button>
	                </li>
	        </ul>
	    </div>
	</form>
</div>
<script type="text/javascript">
//<![CDATA[
var dataForm = new VarienForm('profile_picture', true);

function deleteImage() {
	var deleteImage = confirm('Are you sure you want to delete this image?');
	if(deleteImage) {
		window.location="<?php echo $this->getUrl('customerextend/manage/deletepicture', array('delete' => 1))?>";
		return;
	} else {
		return false;
	}
}
//]]>
</script>