<?php
$propertyTypeId = Mage::helper('property')->getPropertyTypeAttrId();
$propertyTypeAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $propertyTypeId);
$select_protype = '<option value="">'.$this->__('Select').'</option>';
$propertyType = array();
foreach ($propertyTypeAttribute->getSource()->getAllOptions() as $option) {
    $value = $option['value'];
    if($value != '') {
        $propertyType[$value] = $option['label'];
        $select_protype .= "<option value='" . $option['value'] . "'>" . $option['label'] . "</option>";
    }
}

$roomTypeId = Mage::helper('property')->getRoomTypeAttrId();
$roomTypeAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $roomTypeId);
$roomtype_select = '<option value="">'.$this->__('Select').'</option>';
$roomType = array();
foreach ($roomTypeAttribute->getSource()->getAllOptions() as $roomtype_option) {
    $roomtype_value = $roomtype_option['value'];
    if($roomtype_value != '') {
        $roomType[$value] = $roomtype_option['label'];
        $roomtype_select .= "<option value='" . $roomtype_option['value'] . "'>" . $roomtype_option['label'] . "</option>";
    }
}

$amenitiesId = Mage::helper('property')->getAmenitiesAttrId();
$amenitiesAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $amenitiesId);
$countryselect = '';
$countryList = Mage::getResourceModel('directory/country_collection')
                    ->loadData()
                    ->toOptionArray(false);
foreach ($countryList as $country) {
    $value = $country['value'];
    if ($value != '') {
        $countryselect .= "<option value='" . $country['value'] . "'>" . $country['label'] . "</option>";
    }
}

$currencyCountry = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getBaseCurrencyCode())->getName();
$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getBaseCurrencyCode())->getShortName();
?>
<div class="my-account">
	<div class="page-title custom-page" style="margin-bottom:5px;">
	    <h1><?php echo $this->__('About Your Requirement') ?></h1>
	</div>
	<form id="listingform" method="post" name="listingform" action="<?php echo $this->getUrl('listroom/index/post')?>">
		<div class="fieldset">
			<ul class="form-list_inner list_ul">
				<li class="listheading"><h1><?php echo $this->__('Listing Type limit')?></h1></li>
				<p class="required right">* <?php echo $this->__('Required Fields')?></p>
				<li>
					<div class="field">
						<div class="selectproperty">
							<label class="required left lable_inner" for="proptype"> <?php echo $this->__('Property Type')?> <em>*</em></label>
							<div class="floatleft">
								<select class="select select input-text required-entry input-text_pro" name="property_type" id="property_type"><?php echo $select_protype; ?></select>
							</div>
						</div>
					</div>
					<div class="field">
						<div class="selectprivacy">
							<label class="required left lable_inner" for="room_type"> <?php echo $this->__('Room Type')?> <em>*</em></label>
							<div class="floatleft">
								<select class="select select input-text required-entry input-text_room" name="room_type" id="room_type"><?php echo $roomtype_select; ?></select>
							</div>
						</div>
					</div>
				</li>
				
            	
            	<li class="listheading"><h1>Amenities</h1></li>
            	<li style="padding:5px;">
                  <?php
                  $totalAmenity = count($amenitiesAttribute->getSource()->getAllOptions(true, true));
                  ?>
                  <ul id="amenities-value">
                  <?php
                  foreach ($amenitiesAttribute->getSource()->getAllOptions() as $amenity) {
                  	$value = $amenity['value'];
                    if($value !='') {
                        $propertyType[$value] = $amenity['label'];
              	?>
                        <li class="checkbox lable_inner checkbox_inner" style="border:none; padding:5px;">
                    	<input style="float:left;margin:4px;" type="checkbox" name="amenity[]" id="amenity[]" value="<?php echo $amenity['label']; ?>" /> <?php echo $amenity['label']; ?>
                        </li>
              	<?php
                    }
                  }
	            ?>
	              </ul>
	              <div class="clearer"></div>
	            </li>
	            				
				<li class="listheading"><h1><?php echo $this->__('Details') ?></h1></li>
				<li>
 					<div class="field">
 						<div class="input-box_inner">
	                    	<label class="required left lable_inner" for="title"><?php echo $this->__('Title')?> <em>*</em></label>
		                    <div class="floatleft">
		                    	<input type="text" maxlength="100" class="input-text required-entry validate-length minimum-length-4 maximum-length-35 input-text_inner" title="<?php echo $this->__('Title')?>" id="title" name="title">
		                    	<span><?php echo $this->__('Property title should contains 4-35 letters.'); ?></span>
		                   	</div>
	                    </div>
 					</div>
 					<div class="field input-box input-box_inner">
						<label class="required lable_inner left" for="budget_min"> <?php echo $this->__('Budget Min/Night')?> <em>*</em></label>
						<div class="floatleft">
							<input type="text" class="input-text required-entry validate-greater-than-zero input-text_price " value="" title="<?php echo $this->__('Budget Min/Night')?>" id="budget_min" name="budget_min">
							<span><?php echo  $currencySymbol .'('. $this->__('Enter price in ') . $currencyCountry . ')'; ?></span>
						</div>
                	</div>
                	<div class="field input-box input-box_inner">
						<label class="required lable_inner left" for="budget_max"> <?php echo $this->__('Budget Max/Night')?> <em>*</em></label>
						<div class="floatleft">
							<input type="text" class="input-text required-entry validate-greater-than-zero input-text_price " value="" title="<?php echo $this->__('Budget Max/Night')?>" id="budget_max" name="budget_max">
							<span><?php echo  $currencySymbol .'('. $this->__('Enter price in ') . $currencyCountry . ')'; ?></span>
						</div>
                	</div>
 					<div class="field">
 						<div class="input-box_inner">
	                    	<label class="required left lable_inner" for="accommodates "><?php echo $this->__('Accommodates ')?> <em>*</em></label>
		                    <div class="floatleft">
		                    	<input type="text" class="input-text required-entry input-text_inner" title="<?php echo $this->__('Accommodates')?>" id="accommodates" name="accommodates">
		                    	<span><?php echo $this->__('This refers number of guest.'); ?></span>
		                   	</div>
	                    </div>
 					</div>
 					<div class="field">
 						<div class="input-box_inner">
	                    	<label class="required left lable_inner" for="from_date "><?php echo $this->__('From date ')?> <em>*</em></label>
		                    <div class="floatleft">
		                    	<input type="text" class="input-text required-entry input-text_inner" title="<?php echo $this->__('From date')?>" id="from" name="from" placeholder="mm/dd/yyyy" autocomplete="off" style="width:150px !important;">
		                   	</div>
	                    </div>
 					</div>
 					<div class="field">
 						<div class="input-box_inner">
	                    	<label class="required left lable_inner" for="to_date "><?php echo $this->__('To date ')?> <em>*</em></label>
		                    <div class="floatleft">
		                    	<input type="text" class="input-text required-entry input-text_inner" title="<?php echo $this->__('To date')?>" id="to" name="to" placeholder="mm/dd/yyyy" autocomplete="off" style="width:150px !important;">
		                   	</div>
	                    </div>
 					</div> 					                	
                	<script type="text/javascript">
		            $j(function() {
					        var dates = $j( "#from, #to" ).datepicker({
					            changeMonth: true,
					            minDate: '+3D',
					            numberOfMonths: 1,
					            onSelect: function( selectedDate ) {
					                var option = this.id == "from" ? "minDate" : "maxDate",
					                instance = $j( this ).data( "datepicker" ),
					                date = $j.datepicker.parseDate(
					                instance.settings.dateFormat ||
					                    $j.datepicker._defaults.dateFormat,
					                selectedDate, instance.settings );
					                dates.not( this ).datepicker( "option", option, date );
					                $j("#from" ).datepicker("option","maxDate","");
					
					                if(this.id == "from"){
					                    instance = $j( this ).data( "datepicker" )
					                    var depart = $j.datepicker.parseDate($j.datepicker._defaults.dateFormat, selectedDate);
					                    depart.setDate(depart.getDate() + 1);
					                    $j("#to" ).datepicker(  "option", "minDate", depart );
					
					                }
					            }
					        });
					    });
		            </script>
                	<div class="field input-box input-box_inner">
	                    <label for="description" class="required left lable_inner"><?php echo $this->__('Description') ?> <em>*</em></label>
	                    <div class="floatleft">
	                    	<textarea name="description" id="description" title="<?php echo $this->__('Description') ?>" class="required-entry input-text input-text_high" cols="5" rows="5"></textarea>
	                    	<div class="clearer"></div>
	                    </div>
	                </div>
	                
                	<div class="field input-box input-box_inner">
	                    <label for="keywords" class="required left lable_inner"><?php echo $this->__('Keywords') ?> <em>*</em></label>
	                    <div class="floatleft">
	                    	<textarea name="keywords" id="keywords" title="<?php echo $this->__('Keywords') ?>" class="required-entry input-text input-text_high" cols="5" rows="5"></textarea>
	                    	<div class="clearer"></div>
	                    	<span><?php echo $this->__('Add comma(,) seperated keywords. Eg: ocean side, transit')?></span>
	                    </div>
	                </div>
	                
                	<div class="field input-box input-box_inner">
	                  <label for="locality" class="required lable_inner left"> <?php echo $this->__('Locality') ?></label>
						<div class="floatleft">
	                    	<input name="locality" id="locality" title="<?php echo $this->__('Locality') ?>" value="" class="input-text input-text_city" type="text"/>
						</div>
	                </div>
                
                	<div class="field input-box input-box_inner">
	                  <label for="city" class="required lable_inner left"> <?php echo $this->__('City') ?> <em>*</em></label>
						<div class="floatleft">
	                    	<input name="city" id="city" title="<?php echo $this->__('City') ?>" value="" class="input-text required-entry input-text_city" type="text"/>
						</div>
                	</div>

                	<div class="field">
                         <div class="selectpropcountry">
                            <label for="country" class="required lable_inner left">  <?php echo $this->__('Country') ?> <em>*</em></label>
                            <div class="floatleft">
                            	<select id="country" name="country" onchange="renderRegion(this.value)" class="select required-entry input-text_country">
                                    <option value=""><?php echo $this->__('Select your Country') ;?></option>
                                    <?php echo $countryselect; ?>
                             	</select>
                            </div>
                        </div>
                    </div>
                    
                    <div class="field input-box input-box_inner">
                  		<label for="state" class="required lable_inner left"> <?php echo $this->__('State / Province / Region') ?> <em>*</em></label>
						<div id="region_placeholder" class="floatleft">
                    		<input name="state" id="state" title="<?php echo $this->__('State / Province / Region') ?>" value="" class="input-text required-entry input-text_state" type="text"/>
						</div>
                	</div>
					<script type="text/javascript">
					function renderRegion(code) {
						$j.ajax({
					        async:true,
					        type: "GET",
					        data: {ccode:code},
					        url: "<?php echo Mage::getBaseUrl() . 'property/search/region' ?>",
					        success: function(data){
					        	if(data != 0) {
					            	$j("#region_placeholder").html(data);
					        	}
					        }
					    });
					}
					</script>
					
                </li>
			</ul>
			<div class="buttons-set">
		        <p class="required ">* <?php echo $this->__('Required Fields')?></p>
		         <button class="button" title="<?php echo $this->__('Submit your requiremnts')?>" type="submit"><?php echo $this->__('Submit your requiremnts')?></button>
		    </div>
		</div>
	</form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var listingForm = new VarienForm('listingform', true);
    //]]>
</script>